# Generated by Django 5.1 on 2025-12-02 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Essay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(help_text="Texto completo da redação.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("submitted", "Enviada"),
                            ("corrected", "Corrigida"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "score_total",
                    models.PositiveIntegerField(
                        blank=True, help_text="Nota final (0 a 1000).", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Aluno que enviou esta redação.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetenceScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c1",
                    models.PositiveIntegerField(default=0, help_text="Competência 1"),
                ),
                (
                    "c2",
                    models.PositiveIntegerField(default=0, help_text="Competência 2"),
                ),
                (
                    "c3",
                    models.PositiveIntegerField(default=0, help_text="Competência 3"),
                ),
                (
                    "c4",
                    models.PositiveIntegerField(default=0, help_text="Competência 4"),
                ),
                (
                    "c5",
                    models.PositiveIntegerField(default=0, help_text="Competência 5"),
                ),
                ("corrected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        help_text="Professor que corrigiu a redação.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "essay",
                    models.OneToOneField(
                        help_text="Redação à qual essas notas pertencem.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_score",
                        to="essays.essay",
                    ),
                ),
            ],
        ),
    ]
