# Generated by Django 5.1 on 2025-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_alter_competencescore_c1_alter_competencescore_c2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='pdf',
            field=models.FileField(blank=True, help_text='Arquivo PDF da redação (upload manual ou automático)', null=True, upload_to='pdfs/'),
        ),
    ]
